# Generated by Django 5.1.7 on 2025-03-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDS011Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('P1', models.FloatField()),
                ('durP1', models.FloatField()),
                ('ratioP1', models.FloatField()),
                ('P2', models.FloatField()),
                ('durP2', models.FloatField()),
                ('ratioP2', models.FloatField()),
            ],
            options={
                'db_table': 'sds011_metric',
            },
        ),
    ]
