# Generated by Django 5.1.7 on 2025-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feinstaub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHT22Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lan', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'db_table': 'dht22_metric',
            },
        ),
    ]
