# Generated by Django 5.1.7 on 2025-03-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feinstaub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dht22metric',
            old_name='lan',
            new_name='lat',
        ),
    ]
